version: "3.9"
services:

  geohub:
    image: ghcr.io/KenTech-Enterprises-LLC/geohub:main
    env_file:
      - .env
      - .env.beta
    environment:
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    volumes:
      - .env:/usr/src/app/.env
      - .env.beta:/usr/src/app/.env.beta
    ports:
      - "6789:6789"
